services:
  - type: web
    name: he-thong-dieu-phieu-minh-khoi
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
